---
# tasks file for k8s-slave
- name: Installing docker Package
  package:
    name: 
    - docker
    - iproute-tc
    state: present

- name: Starting docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copying content of the daemon.json file
  copy:
    dest: /etc/docker/daemon.json
    content: |
            {
                "exec-opts": ["native.cgroupdriver=systemd"]
            }
  register: out

- name: Restarting docker service
  service:
    name: docker
    state: restarted
  when: out.changed == true

- name: Configuring Yum repo for k8s
  yum_repository:
    description: Yum for k8s
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
    exclude:
    - kubelet
    - kubeadm
    - kubectl

- name: Installing kubeadm
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: Enabling docker and kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Copying k8s.conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
  register: out1

- name: Refreshing sysctl
  shell: "sysctl --system"
  when: out1.changed == true
